// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGuSojnxKx6PLTTAYy7qk8Zzhq9Tz8Hcg',
    appId: '1:1057309683566:web:eeb1e5401b4d48bcb2db7f',
    messagingSenderId: '1057309683566',
    projectId: 'eduzap-ae9d6',
    authDomain: 'eduzap-ae9d6.firebaseapp.com',
    databaseURL: 'https://eduzap-ae9d6-default-rtdb.firebaseio.com',
    storageBucket: 'eduzap-ae9d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9yxzi0zUBD3Lpb0MhxYdSexqHJl7wAr8',
    appId: '1:1057309683566:android:c06446ccff03d892b2db7f',
    messagingSenderId: '1057309683566',
    projectId: 'eduzap-ae9d6',
    databaseURL: 'https://eduzap-ae9d6-default-rtdb.firebaseio.com',
    storageBucket: 'eduzap-ae9d6.appspot.com',
  );
}
